services:

  minio:
    image: minio/minio
    container_name: medical-pipeline-minio

    command: server /data --console-address ":9001"

    ports:
      - "9010:9000"
      - "9011:9001"

    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}

    volumes:
      - minio_data:/data

  pipeline:
    build: .

    container_name: medical-pipeline

    depends_on:
      - minio

    environment:
      HMAC_SECRET: ${HMAC_SECRET}

      MINIO_ENDPOINT: minio:9000
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_BUCKET: ${MINIO_BUCKET}

    volumes:
      - ./data:/app/data
      - ./output:/app/output
      - ./config:/app/config

volumes:
  minio_data: